version: "3"
services:
  mysql:
    container_name: mysql_host
    build:
      context: docker_mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker_mysql/data:/var/lib/mysql
      - ./docker_mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker_mysql/sql:/docker-entrypoint-initdb.d 
    # ports:
    # - 11000:3306
    command: mysqld